version: "3.9"

services:

  postgres:
    image: postgres:14.2
    environment:
      POSTGRES_USER: rails 
      POSTGRES_PASSWORD: EDGk5vCM9b57
    ports: 
      - '5432:5432'
    volumes:
      - postgres-db:/var/lib/postgresql/data

  redis:
    image: redis:7.0
    ports:
      - '6379:6379'
    volumes:
      - redis-db:/var/lib/redis/data

  web:
    build: .
    volumes:
      - .:/myapp
    links:
      - postgres
      - redis
    ports:
      - '3000:3000'
    env_file:
      - .env

  sidekiq:
    build:
      context: .
    command: bundle exec sidekiq 
    volumes:
      - .:/myapp
    links:
      - postgres
      - redis
    env_file:
      - .env

volumes:
  postgres-db:
  redis-db:
