version: "3.9"

services:

  postgres:
    image: postgres:14.2
    environment:
      POSTGRES_USER: rails 
      POSTGRES_PASSWORD: EDGk5vCM9b57
    networks:
      - graphqts
    volumes:
      - postgres-db:/var/lib/postgresql/data

  cache:
    image: redis:7.0
    networks:
      - graphqts
    volumes:
      - redis-db:/data

  web:
    image: crypt1d/graphprotocol-qts
    command: /bin/bash -c "rails db:create && rails db:migrate && rails server -b 0.0.0.0"
    ports:
      - 3000:3000
    networks:
      - graphqts
    depends_on:
      - cache 
      - postgres 
    env_file:
      - .env
    deploy:
      placement:
        constraints: [node.role == manager]

  sidekiq-imports:
    image: crypt1d/graphprotocol-qts
    deploy:
      placement:
        constraints: [node.role == manager]
    networks:
      - graphqts
    depends_on:
      - cache
      - postgres
      - web
    command: bundle exec sidekiq -q imports
    env_file:
      - .env
    stop_grace_period: 60s

  sidekiq:
    image: crypt1d/graphprotocol-qts
    deploy:
      mode: replicated
      replicas: 3
      placement:
        constraints: [node.role == worker]
    networks:
      - graphqts
    depends_on:
      - cache 
      - postgres 
      - web
    command: bundle exec sidekiq 
    env_file:
      - .env
    stop_grace_period: 60s 

volumes:
  postgres-db:
  redis-db:
  tmp-vol:

networks:
  graphqts:
