# SQLite. Versions 3.8.0 and up are supported.
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem "sqlite3"
#
default: &default
  adapter: postgresql 
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 50 } %>
  port: 5432
  host: <%= ENV.fetch("POSTGRES_HOST") { "localhost" } %>
  username: <%= ENV.fetch("POSTGRES_USERNAME") { "rails" } %>
  password: <%= ENV.fetch("POSTGRES_PASSWORD") %>

development:
  <<: *default
  database: <%= ENV.fetch("POSTGRES_DATABASE") { "graph_protocol_qts_dev" } %>

test:
  <<: *default
  database: <%= ENV.fetch("POSTGRES_DATABASE") { "graph_protocol_qts_test" } %>

production:
  <<: *default
  database: <%= ENV.fetch("POSTGRES_DATABASE") { "graph_protocol_qts_prod" } %>
